module.exports = [
    "Arc'teryx",
    'Big Agnes',
    'Black Diamond',
    'Camp',
    'Cascade Designs',
    'CamelBak',
    'Cotopaxi',
    'Deuter',
    'Dynafit',
    'Enlightened Equipment',
    'Exped',
    'Fjällräven',
    'Garmin',
    'Goal Zero',
    'Gossamer Gear',
    'Granite Gear',
    'Gregory',
    'GSI Outdoors',
    'Helinox',
    'Hilleberg',
    'Hydrapak',
    'Hyperlite Mountain Gear',
    'Inov-8',
    'Jetboil',
    'Katabatic Gear',
    'Katadyn',
    'Kelty',
    'Klymit',
    'Kokopelli',
    'La Sportiva',
    'Leki',
    'Locus Gear',
    'Mammut',
    'Marmot',
    'Merrell',
    'MLD (Mountain Laurel Designs)',
    'Montbell',
    'Mountain Equipment',
    'Mountain Hardwear',
    'MSR',
    'Mystery Ranch',
    'Naturehike',
    'Nemo',
    'Nitecore',
    'Nunatak',
    'Oboz',
    'Osprey',
    'Outdoor Research',
    "Pa'lante Packs",
    'Patagonia',
    'Petzl',
    'Platypus',
    'Primus',
    'Rab',
    'REI Co-op',
    'Salewa',
    'Salomon',
    'Sawyer',
    'Scarpa',
    'Sea to Summit',
    'Sierra Designs',
    'Six Moon Designs',
    'Snow Peak',
    'Soto',
    'Suunto',
    'Tarptent',
    'Thermarest',
    'TNF (The North Face)',
    'Toaks',
    'Trail Designs',
    'ULA Equipment',
    'Ursack',
    'Western Mountaineering',
    'Zpacks',
];
